# Generated by Django 4.2.28 on 2026-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_diarynote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
