# Generated by Django 4.2.28 on 2026-03-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dictionaryterm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictionaryTerm',
            new_name='Dictionary',
        ),
    ]
